// Code generated by "esc -pkg view -o api/view/views.go -include .*\.html -prefix=api/view api/view"; DO NOT EDIT.

package view

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/groups.html": {
		name:    "groups.html",
		local:   "api/view/groups.html",
		size:    3111,
		modtime: 1600425148,
		compressed: `
H4sIAAAAAAAC/+xWTW/zRBC+51eMlnKr07SlSESOEeoFCfVDAnGNxvHY2cbeTXc3oZEbiRsSXPgDSHDg
yBGp4sCvqYr4F692YzeJa7vu+17fHqzux8w888wzk+35EV/CJEWtR2yOCRdopGJBDwAgz4HH0P8a9bWi
JazXbtf++VjahEZAaITHRSwZTBXFI5bn0L9GM4X1+ksZx5rMyG0pWl65JazXDJRMacTChTFSsODx4efH
hx///+Nv/wifo5OIbNQKmEu6M+1g5opnqFav4Cn8vETySyMS/yjiy6CX56BQJAQH/BAOMp3AcAT9C9Ia
E9Iltn1qBaXgvl5EMS5SU5Bce9ObEkZcJCzw9RzF/pmmWwY8cnnZ4P1v6fZykdlUAh+LnD+pOXy5Z1P0
j2yIAPwwyHOI0JDhGQE7GQw+9wbH3uAEjs+Gg8+GgzO2MT9XhIair4zzEAYFK83ZhDJa7aRbvZSRwcpx
9cpECoNckPLidMGjmttbjaQkNji/w0TDPSQGBrt6aYuj5A8NvutRpZ7OvNNKmVIMKQX39fRiMiGtWfD0
+0///fVvQXaFsY5xvngFWkHBrjStMLdctJCwF7opGdfkgVORK73LpQukon1ag7ZT0nLc7r97dd9Y2XLI
BE+//fn0z6/dKvseVS2b9krxhItWITfHbqevqhgtlRlnOB9PFxkWzXRBBtuCb3ovlipDA+zTpZ0V/e8x
XRDcgyBg7FUF7FcKMEIhtTdB4cUyjTqI/40V3JFz/xtabSXdoT0/oEWd6VxRabq0JHmhvHNYGhhUlMkl
jSmbm9U45YIc2rmiDjA7DJv2K+0d1nxa47Zua4dGTEmZut+LBqXeaCnGcYrGlEP/XApDwsBpl4FgzT3L
ZttY2JWPM5jRqlY2vS7Vdh5cyZ0PHgPdlp6YNjiZ2UbZpnpzCAezmlQLZRx3GeoW66zACsNiubF3oTbl
s/+kuth6DrBzoUVvDQLauuw18WJJsKntV68xWL3Yqi+Q7XL7Yisfkx9fvG9/8b4LAAD//+ybhUInDAAA
`,
	},

	"/": {
		name:  "/",
		local: `api/view`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"api/view": {
		_escData["/groups.html"],
	},
}
