// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type NewRule struct {
	Name            string        `json:"name"`
	Description     *string       `json:"description"`
	Interval        int           `json:"interval"`
	Threshold       int           `json:"threshold"`
	Priority        int           `json:"priority"`
	Rule            string        `json:"rule"`
	Template        *string       `json:"template"`
	SummaryTemplate *string       `json:"summary_template"`
	Triggers        []*NewTrigger `json:"triggers"`
	Status          *string       `json:"status"`
}

type NewTrigger struct {
	PreCondition string `json:"pre_condition"`
	Action       string `json:"action"`
}

type NewUser struct {
	Name   string         `json:"name"`
	Metas  []*NewUserMeta `json:"metas"`
	Status string         `json:"status"`
}

type NewUserMeta struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Rule struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	Description     string     `json:"description"`
	Interval        int        `json:"interval"`
	Threshold       int        `json:"threshold"`
	Priority        int        `json:"priority"`
	Rule            string     `json:"rule"`
	Template        string     `json:"template"`
	SummaryTemplate string     `json:"summary_template"`
	Triggers        []*Trigger `json:"triggers"`
	Status          string     `json:"status"`
	CreatedAt       string     `json:"created_at"`
	UpdatedAt       string     `json:"updated_at"`
}

type Trigger struct {
	ID           string `json:"id"`
	PreCondition string `json:"pre_condition"`
	Action       string `json:"action"`
}

type User struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Metas     []*UserMeta `json:"metas"`
	Status    string      `json:"status"`
	CreatedAt string      `json:"created_at"`
	UpdatedAt string      `json:"updated_at"`
}

type UserMeta struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type UserPagination struct {
	HasNext bool    `json:"hasNext"`
	Users   []*User `json:"users"`
	Cursor  int     `json:"cursor"`
}
