// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type NewRule struct {
	Name            string        `json:"name"`
	Description     *string       `json:"description"`
	Interval        int           `json:"interval"`
	Threshold       int           `json:"threshold"`
	Priority        int           `json:"priority"`
	Rule            string        `json:"rule"`
	Template        *string       `json:"template"`
	SummaryTemplate *string       `json:"summary_template"`
	Triggers        []*NewTrigger `json:"triggers"`
	Status          *string       `json:"status"`
}

type NewTrigger struct {
	PreCondition string `json:"pre_condition"`
	Action       string `json:"action"`
}

type Rule struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	Description     string     `json:"description"`
	Interval        int        `json:"interval"`
	Threshold       int        `json:"threshold"`
	Priority        int        `json:"priority"`
	Rule            string     `json:"rule"`
	Template        string     `json:"template"`
	SummaryTemplate string     `json:"summary_template"`
	Triggers        []*Trigger `json:"triggers"`
	Status          string     `json:"status"`
	CreatedAt       string     `json:"created_at"`
	UpdatedAt       string     `json:"updated_at"`
}

type Trigger struct {
	ID           string `json:"id"`
	PreCondition string `json:"pre_condition"`
	Action       string `json:"action"`
}
